
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbGameConst
{

     private readonly GameConst _data;

     public GameConst Data => _data;

    public TbGameConst(JSONNode _buf)
    {
        int n = _buf.Count;
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        { if(!_buf[0].IsObject) { throw new SerializationException(); }  _data = GameConst.DeserializeGameConst(_buf[0]);  }
    }


    /// <summary>
    /// 描述2
    /// </summary>
     public int X1 => _data.X1;
    /// <summary>
    /// 描述3
    /// </summary>
     public string X2 => _data.X2;
    /// <summary>
    /// 描述4
    /// </summary>
     public float X3 => _data.X3;
    /// <summary>
    /// 描述5
    /// </summary>
     public System.Collections.Generic.List<int> X4 => _data.X4;
    /// <summary>
    /// 描述6
    /// </summary>
     public System.Collections.Generic.List<string> X5 => _data.X5;
    /// <summary>
    /// 描述8
    /// </summary>
     public string[] X7 => _data.X7;
    /// <summary>
    /// 描述9
    /// </summary>
     public long X8 => _data.X8;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

