
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ui
{
public partial class TbUIPanel
{
    private readonly System.Collections.Generic.Dictionary<int, ui.UIPanel> _dataMap;
    private readonly System.Collections.Generic.List<ui.UIPanel> _dataList;
    
    public TbUIPanel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ui.UIPanel>();
        _dataList = new System.Collections.Generic.List<ui.UIPanel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ui.UIPanel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ui.UIPanel.DeserializeUIPanel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ui.UIPanel> DataMap => _dataMap;
    public System.Collections.Generic.List<ui.UIPanel> DataList => _dataList;

    public ui.UIPanel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ui.UIPanel Get(int key) => _dataMap[key];
    public ui.UIPanel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

