
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.ui
{
public partial class TbUILayer
{
    private readonly System.Collections.Generic.Dictionary<int, ui.UILayer> _dataMap;
    private readonly System.Collections.Generic.List<ui.UILayer> _dataList;
    
    public TbUILayer(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ui.UILayer>();
        _dataList = new System.Collections.Generic.List<ui.UILayer>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ui.UILayer _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ui.UILayer.DeserializeUILayer(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ui.UILayer> DataMap => _dataMap;
    public System.Collections.Generic.List<ui.UILayer> DataList => _dataList;

    public ui.UILayer GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ui.UILayer Get(int key) => _dataMap[key];
    public ui.UILayer this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

