// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DefineMsg.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from DefineMsg.proto</summary>
  public static partial class DefineMsgReflection {

    #region Descriptor
    /// <summary>File descriptor for DefineMsg.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DefineMsgReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9EZWZpbmVNc2cucHJvdG8SCHByb3RvY29sKqAHCgdFUlJDT0RFEgkKBUVD",
            "X09LEAASDgoKRUNfQkFHRlVMTBABEhEKDUVDX01PTkVZTElNSVQQAhIWChJF",
            "Q19JTlBVVExFTklOVkFMSUQQAxIPCgtFQ19URU1QREFUQRAEEhEKDUVDX0xF",
            "VkVMTElNSVQQBRISCg5FQ19ST0xFT0ZGTElORRAGEhMKD0VDX01TR1NFUklB",
            "TElaRRAHEhkKFUVDX01BVEVSSUFMX05PVEVOT1VHSBAIEhkKFUVDX0NMSUVO",
            "VERBVEFfSU5WQUxJRBAJEhUKEUVDX1JPTEVMVkVMX0xJTUlUEAoSEwoPRUNf",
            "Uk9MRUFDX0xJTUlUEAsSFwoTRUNfU0tJTExQT0lOVF9MSU1JVBAMEhIKDkVD",
            "X0NPVU5UX0xJTUlUEA0SDQoJRUNfQUNfTUFYEA4SDgoKRUNfQ0hBVF9DRBAP",
            "EhMKD0VDX0xPR0lOX0xPR0lORxBkEhkKFUVDX0xPR0lOX1NUQVRFSU5WQUxJ",
            "RBBlEhcKE0VDX0xPR0lOX05FRURDUkVBVEUQZhIYChRFQ19MT0dJTl9BQ0NP",
            "VU5UX0VSUhBnEhcKE0VDX0xPR0lOX1BBU1NXRF9FUlIQaBIYChRFQ19DUkVB",
            "VEVfTkFNRVJFUEVBVBBpEhUKEUVDX0NSRUFURV9CQURXT1JEEGoSFwoTRUNf",
            "TE9HSU5fU0VSVkVSRlVMTBBrEhMKD0VDX0NSRUFURV9FWElTVBBsEhUKEEVD",
            "X0hFUk9MRVZFTF9NQVgQyAESFAoPRUNfSEVST19OT1RGSU5EEMkBEhQKD0VD",
            "X0hFUk9TVEFSX01BWBDKARIVChBFQ19IRVJPR1JBREVfTUFYEMsBEhcKEkVD",
            "X0hFUk9HUkFERV9MSU1JVBDMARIdChhFQ19IRVJPX01JU1NJT05PQkpfTElN",
            "SVQQzQESHQoYRUNfSEVST19NSVNTSU9OUFJFX0xJTUlUEM4BEh4KGUVDX0hF",
            "Uk9fVEFMRU5UUE9JTlRfTElNSVQQ0AESHAoXRUNfSEVST19UQUxFTlRQUkVf",
            "TElNSVQQ0QESHAoXRUNfSEVST19UQUxFTlRfSEFTTEVBUk4Q0gESHgoZRUNf",
            "SEVST19NSVNTSU9OX0hBU0ZJTklTSBDTARIXChJFQ19TV0VFUF9TVEFSTElN",
            "SVQQrAISGAoTRUNfU1dFRVBfQ09VTlRMSU1JVBCtAhIZChRFQ19SQUZGTEVf",
            "Q09VTlRMSU1JVBCQAyrHAQoMSXRlbVR5cGVFbnVtEhIKDkl0ZW1UeXBlX01v",
            "bmV5EAASEQoNSXRlbVR5cGVfQ2FyZBABEhcKE0l0ZW1UeXBlX0NhcmREZWJy",
            "aXMQAhIUChBJdGVtVHlwZV9EZXZlbG9wEAMSEwoPSXRlbVR5cGVfTWFuYWdl",
            "EAQSEAoMSXRlbVR5cGVfQm94EAUSFAoQSXRlbVR5cGVfSGVyb0V4cBAGEhMK",
            "D0l0ZW1UeXBlX1JhZmZsZRAHEg8KC0l0ZW1UeXBlX0FDEAgqfgoNRXF1aXBU",
            "eXBlRW51bRIOCgpFcXVpcF9Ob25lEAASDQoJRXF1aXBIZWFkEAESEAoMRXF1",
            "aXBDbG90aGVzEAISDwoLRXF1aXBXZWFwb24QAxINCglFcXVpcFdpbmcQBBIN",
            "CglFcXVpcFJpZGUQBRINCglFcXVpcEZhY2UQBirMAgoPUmVzb3VyY2VTcmNF",
            "bnVtEgoKBlNyY19HTRAAEgsKB1NyY19QVkUQARILCgdTcmNfUFZCEAISDAoI",
            "U3JjX0dpZnQQBBIOCgpTcmNfR2F0aGVyEAUSDAoIU3JjX1Rhc2sQBxIPCgtT",
            "cmNfT3BlbkJveBAIEg8KC1NyY19MZXZlbFVwEAkSDAoIU3JjX01haWwQChIN",
            "CglTcmNfRmlnaHQQCxIVChFTcmNfQ2hhcHRlclJld2FyZBAMEhQKEFNyY19U",
            "YWxlbnRSZXdhcmQQDRIOCgpTcmNfUmFmZmxlEA4SFQoRU3JjX0hlcm9EZWNv",
            "bXBvc2UQDxIQCgxTcmNfUXVpY2tCdXkQEBINCglTcmNfU3RvcmUQERIPCgtT",
            "cmNfSXRlbVVzZRASEg8KC1NyY19GdW5jQnV5EBMSEQoNU3JjX0FjUmVjb3Zl",
            "chAUKr0CCg9SZXNvdXJjZURlY0VudW0SCgoGRGVjX0dNEAASFgoSRGVjX0J1",
            "eVNob3BQcm9kdWN0EAMSFgoSRGVjX1Nob3BQcm9kdWN0UmVmEAQSEwoPRGVj",
            "X0hlcm9MZXZlbFVwEAUSEgoORGVjX0hlcm9TdGFyVXAQBhITCg9EZWNfSGVy",
            "b0dyYWRlVXAQBxISCg5EZWNfRmlnaHRTd2VlcBAIEhAKDERlY19UZWFtT3Bl",
            "bhAJEg4KCkRlY19SYWZmbGUQChIQCgxEZWNfUXVpY2tCdXkQCxINCglEZWNf",
            "U3RvcmUQDBIRCg1EZWNfUm9sZVNraWxsEA0SDwoLRGVjX0l0ZW1Vc2UQDhIN",
            "CglEZWNfQnV5QWMQDxISCg5EZWNfQ291bnRHcm91cBAQEhIKDkRlY19IZXJv",
            "VGFsZW50EBEqwQEKDU1vbmV5VHlwZUVudW0SDQoJTW9uZXlOb25lEAASDQoJ",
            "TW9uZXlHb2xkEAESEQoNTW9uZXlEaWFubW9uZBACEhUKEU1vbmV5QmluZERp",
            "YW5tb25kEAMSCwoHTW9uZXlBQxAFEg4KCk1vbmV5QXJlbmEQBhIVChFNb25l",
            "eUludGVsbGlnZW5jZRAHEg8KC01vbmV5UmFmZmxlEAgSEwoPTW9uZXlTa2ls",
            "bFBvaW50EAkSDgoKTW9uZXlNYXhBQxAKKmsKD1Nob3BSZWZSdWxlRW51bRIT",
            "Cg9SZWZSdWxlX0RlZmF1bHQQABIQCgxSZWZSdWxlX1JhbmQQARIbChdSZWZS",
            "dWxlX1JhbmROb3RSZXBlYXRlZBACEhQKEFJlZlJ1bGVfU2VxdWVuY2UQAyr3",
            "BQoORWZmZWN0VHlwZUVudW0SCwoHRVRfSHVydBAAEg0KCUVUX1BvaXNvbhAB",
            "EgsKB0VUX0N1cmUQAhILCgdFVF9Hb2xkEAMSDgoKRVRfU2lsZW5jZRAEEgwK",
            "CEVUX0Rpenp5EAUSDAoIRVRfU2xlZXAQBhIOCgpFVF9Ta2lsbENkEAcSEQoN",
            "RVRfU3VidmVyc2l2ZRAIEgwKCEVUX0JsZWVkEAoSDgoKRVRfQ291bnRlchAW",
            "EgwKCEVUX0xlZWNoEBcSDgoKRVRfUmVjb3ZlchAYEhcKE0VUX0NoYW5nZUJ1",
            "ZmZSb3VuZDEQGhIXChNFVF9DaGFuZ2VCdWZmUm91bmQyEBsSFwoTRVRfQ2hh",
            "bmdlQnVmZlJvdW5kMxAcEhcKE0VUX0NoYW5nZUJ1ZmZSb3VuZDQQHRIYChRF",
            "VF9DaGFuZ2VTa2lsbFJvdW5kMRAeEhgKFEVUX0NoYW5nZVNraWxsUm91bmQy",
            "EB8SDgoKRVRfTXVzdEhpdBAgEg0KCUVUX1VuTWlzcxAhEg0KCUVUX0ltbXVu",
            "ZRAiEgwKCEVUX1RhdW50ECMSEgoORVRfTXVsdGlBY3Rpb24QJBIMCghFVF9D",
            "aGFvcxAlEhEKDUVUX0ZvcmJpZFBBU1YQJhIPCgtFVF9TaGllbGRVcBBkEg4K",
            "CkVUX01heEhwVXAQZRIQCgxFVF9NYXhIcERvd24QZhIMCghFVF9BdGtVcBBn",
            "Eg4KCkVUX0F0a0Rvd24QaBIMCghFVF9EZWZVcBBpEg4KCkVUX0RlZkRvd24Q",
            "ahIMCghFVF9Eb2RVcBBrEg4KCkVUX0RvZERvd24QbBINCglFVF9Dcml0VXAQ",
            "bRIPCgtFVF9Dcml0RG93bhBuEhMKD0VUX0NyaXREYW1hZ2VVcBBvEhUKEUVU",
            "X0NyaXREYW1hZ2VEb3duEHASEAoMRVRfQ3JpdERlZlVwEHESEgoORVRfQ3Jp",
            "dERlZkRvd24QchIMCghFVF9IaXRVcBBzEg4KCkVUX0hpdERvd24QdCrAAQoF",
            "RVBST1ASDQoJUFJPUF9OT05FEAASCwoHUFJPUF9IUBABEg4KClBST1BfTUFY",
            "SFAQAhIMCghQUk9QX0FUSxADEgwKCFBST1BfREVGEAQSDAoIUFJPUF9ET0QQ",
            "BRINCglQUk9QX0NSSVQQBhIPCgtQUk9QX1NISUVMRBAHEgwKCFBST1BfSElU",
            "EAgSEwoPUFJPUF9DUklUREFNQUdFEAkSEAoMUFJPUF9DUklUREVGEAoSDAoI",
            "UFJPUF9OdW0QCyo8Cg5FbnRpdHlUeXBlRW51bRILCgdFVF9IZXJvEAASDgoK",
            "RVRfTW9uc3RlchABEg0KCUVUX1BsYXllchACKnkKDVNraWxsVHlwZUVudW0S",
            "EgoOU2tpbGxUeXBlX05vbmUQABIUChBTa2lsbFR5cGVfTm9ybWFsEAESFAoQ",
            "U2tpbGxUeXBlX1VuaXF1ZRACEhIKDlNraWxsVHlwZV9QQVNWEAMSFAoQU2tp",
            "bGxUeXBlX1BsYXllchAEKmQKDVNraWxsQXJlYUVudW0SFQoRU2tpbGxBcmVh",
            "X0ludmFsaWQQABIRCg1Ta2lsbEFyZWFfQWxsEAESEwoPU2tpbGxBcmVhX0Zy",
            "b250EAISFAoQU2tpbGxBcmVhX0JlaGluZBADKk0KDVNraWxsQ2FtcEVudW0S",
            "EwoPU2tpbGxDYW1wX0VuZW15EAASFAoQU2tpbGxDYW1wX0ZyaWVuZBABEhEK",
            "DVNraWxsQ2FtcF9BbGwQAipxCg5UYXJnZXRUeXBlRW51bRITCg9Ta2lsbFR5",
            "cGVTaW5nbGUQABIQCgxTa2lsbFR5cGVBbGwQARIRCg1Ta2lsbFR5cGVSYW5k",
            "EAISEgoOU2tpbGxUeXBlTWluSHAQAxIRCg1Ta2lsbFR5cGVTZWxmEAQqvQEK",
            "EkZpZ2h0Q29uZGl0aW9uRW51bRIeChpGaWdodENvbmRpdGlvbl9FbmVteUFs",
            "bERpZRAAEh8KG0ZpZ2h0Q29uZGl0aW9uX0VuZW15SGVyb0RpZRABEiMKH0Zp",
            "Z2h0Q29uZGl0aW9uX0ZpcmVuZEFsaXZlQ291bnQQAhIgChxGaWdodENvbmRp",
            "dGlvbl9GcmllbmRIZXJvRGllEAMSHwobRmlnaHRDb25kaXRpb25fRnJpZW5k",
            "QWxsRGllEAQqhgEKEkhlcm9NaXNzaW9uT2JqRW51bRITCg9IZXJvT2JqX0lu",
            "dmFsaWQQABIRCg1IZXJvT2JqX0xldmVsEAESDwoLSGVyb09ial9XaW4QAhIR",
            "Cg1IZXJvT2JqX0dyYWRlEAMSEAoMSGVyb09ial9TdGFyEAQSEgoOSGVyb09i",
            "al9MaW5rVXAQBSqpAQoUSGVyb1RhbGVudFJld2FyZEVudW0SGAoUVGFsZW50",
            "UmV3YXJkX0ludmFsaWQQABIVChFUYWxlbnRSZXdhcmRfUHJvcBABEhUKEVRh",
            "bGVudFJld2FyZF9CVUZGEAISFQoRVGFsZW50UmV3YXJkX0lDb24QAxIXChNU",
            "YWxlbnRSZXdhcmRfTGlua1VwEAQSGQoVVGFsZW50UmV3YXJkX1Jlc291cmNl",
            "EAUqVwoOUmFmZmxlVHlwZUVudW0SFgoSUmFmZmxlVHlwZV9JbnZhbGlkEAAS",
            "EwoPUmFmZmxlVHlwZV9IZXJvEAESGAoUUmFmZmxlVHlwZV9GdXJuaXR1cmUQ",
            "AipNCg9IZXJvUXVhbGl0eUVudW0SEwoPSGVyb1F1YWxpdHlfU1NSEAASEgoO",
            "SGVyb1F1YWxpdHlfU1IQARIRCg1IZXJvUXVhbGl0eV9SEAIqQAoSRGlmZmlj",
            "dWx0eVR5cGVFbnVtEhUKEURpZmZpY3VsdHlfTm9ybWFsEAASEwoPRGlmZmlj",
            "dWx0eV9IYXJkEAEqSQoMRnVuY1B1cmNUeXBlEhQKEEZ1bmNQdXJjX0ludmFs",
            "aWQQABIPCgtGdW5jUHVyY19BQxABEhIKDkZ1bmNQdXJjX0FyZW5hEAIqZQoM",
            "QnVmZlR5cGVFbnVtEhQKEEJ1ZmZUeXBlX0ludmFsaWQQABIRCg1CdWZmVHlw",
            "ZV9CdWZmEAESEwoPQnVmZlR5cGVfRGVidWZmEAISFwoTQnVmZlR5cGVfTmV1",
            "dHJhbGl0eRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ERRCODE), typeof(global::Protocol.ItemTypeEnum), typeof(global::Protocol.EquipTypeEnum), typeof(global::Protocol.ResourceSrcEnum), typeof(global::Protocol.ResourceDecEnum), typeof(global::Protocol.MoneyTypeEnum), typeof(global::Protocol.ShopRefRuleEnum), typeof(global::Protocol.EffectTypeEnum), typeof(global::Protocol.EPROP), typeof(global::Protocol.EntityTypeEnum), typeof(global::Protocol.SkillTypeEnum), typeof(global::Protocol.SkillAreaEnum), typeof(global::Protocol.SkillCampEnum), typeof(global::Protocol.TargetTypeEnum), typeof(global::Protocol.FightConditionEnum), typeof(global::Protocol.HeroMissionObjEnum), typeof(global::Protocol.HeroTalentRewardEnum), typeof(global::Protocol.RaffleTypeEnum), typeof(global::Protocol.HeroQualityEnum), typeof(global::Protocol.DifficultyTypeEnum), typeof(global::Protocol.FuncPurcType), typeof(global::Protocol.BuffTypeEnum), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///通用定义文件
  /// </summary>
  public enum ERRCODE {
    /// <summary>
    ///通用错误定义 0 ~ 100
    /// </summary>
    [pbr::OriginalName("EC_OK")] EcOk = 0,
    /// <summary>
    ///背包满
    /// </summary>
    [pbr::OriginalName("EC_BAGFULL")] EcBagfull = 1,
    /// <summary>
    ///货币不足
    /// </summary>
    [pbr::OriginalName("EC_MONEYLIMIT")] EcMoneylimit = 2,
    /// <summary>
    ///输入长度无效
    /// </summary>
    [pbr::OriginalName("EC_INPUTLENINVALID")] EcInputleninvalid = 3,
    /// <summary>
    ///模板数据错误
    /// </summary>
    [pbr::OriginalName("EC_TEMPDATA")] EcTempdata = 4,
    /// <summary>
    ///等级不足
    /// </summary>
    [pbr::OriginalName("EC_LEVELLIMIT")] EcLevellimit = 5,
    /// <summary>
    ///玩家已离线
    /// </summary>
    [pbr::OriginalName("EC_ROLEOFFLINE")] EcRoleoffline = 6,
    /// <summary>
    ///消息序列化失败
    /// </summary>
    [pbr::OriginalName("EC_MSGSERIALIZE")] EcMsgserialize = 7,
    /// <summary>
    ///所需材料不足
    /// </summary>
    [pbr::OriginalName("EC_MATERIAL_NOTENOUGH")] EcMaterialNotenough = 8,
    /// <summary>
    ///客户端发来的数据无效
    /// </summary>
    [pbr::OriginalName("EC_CLIENTDATA_INVALID")] EcClientdataInvalid = 9,
    /// <summary>
    ///玩家等级不足
    /// </summary>
    [pbr::OriginalName("EC_ROLELVEL_LIMIT")] EcRolelvelLimit = 10,
    /// <summary>
    ///玩家体力点不足
    /// </summary>
    [pbr::OriginalName("EC_ROLEAC_LIMIT")] EcRoleacLimit = 11,
    /// <summary>
    ///玩家技能升级，技能点不足
    /// </summary>
    [pbr::OriginalName("EC_SKILLPOINT_LIMIT")] EcSkillpointLimit = 12,
    /// <summary>
    ///次数不足
    /// </summary>
    [pbr::OriginalName("EC_COUNT_LIMIT")] EcCountLimit = 13,
    /// <summary>
    ///体力上限
    /// </summary>
    [pbr::OriginalName("EC_AC_MAX")] EcAcMax = 14,
    /// <summary>
    ///聊天CD
    /// </summary>
    [pbr::OriginalName("EC_CHAT_CD")] EcChatCd = 15,
    /// <summary>
    ///角色相关错误码定义 100
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_LOGING")] EcLoginLoging = 100,
    /// <summary>
    ///登录状态无效
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_STATEINVALID")] EcLoginStateinvalid = 101,
    /// <summary>
    ///需要创建角色
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_NEEDCREATE")] EcLoginNeedcreate = 102,
    /// <summary>
    ///账号无效
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_ACCOUNT_ERR")] EcLoginAccountErr = 103,
    /// <summary>
    ///密码无效
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_PASSWD_ERR")] EcLoginPasswdErr = 104,
    /// <summary>
    ///名字被占用
    /// </summary>
    [pbr::OriginalName("EC_CREATE_NAMEREPEAT")] EcCreateNamerepeat = 105,
    /// <summary>
    ///非法字符
    /// </summary>
    [pbr::OriginalName("EC_CREATE_BADWORD")] EcCreateBadword = 106,
    /// <summary>
    ///服务器人满
    /// </summary>
    [pbr::OriginalName("EC_LOGIN_SERVERFULL")] EcLoginServerfull = 107,
    /// <summary>
    ///创建角色角色已经存在
    /// </summary>
    [pbr::OriginalName("EC_CREATE_EXIST")] EcCreateExist = 108,
    /// <summary>
    ///英雄养成相关错误码 200
    /// </summary>
    [pbr::OriginalName("EC_HEROLEVEL_MAX")] EcHerolevelMax = 200,
    /// <summary>
    ///英雄未找到
    /// </summary>
    [pbr::OriginalName("EC_HERO_NOTFIND")] EcHeroNotfind = 201,
    /// <summary>
    ///英雄星级满
    /// </summary>
    [pbr::OriginalName("EC_HEROSTAR_MAX")] EcHerostarMax = 202,
    /// <summary>
    ///英雄阶级满
    /// </summary>
    [pbr::OriginalName("EC_HEROGRADE_MAX")] EcHerogradeMax = 203,
    /// <summary>
    ///英雄等阶限制
    /// </summary>
    [pbr::OriginalName("EC_HEROGRADE_LIMIT")] EcHerogradeLimit = 204,
    /// <summary>
    ///英雄任务目标没有达成
    /// </summary>
    [pbr::OriginalName("EC_HERO_MISSIONOBJ_LIMIT")] EcHeroMissionobjLimit = 205,
    /// <summary>
    ///前置任务没有完成
    /// </summary>
    [pbr::OriginalName("EC_HERO_MISSIONPRE_LIMIT")] EcHeroMissionpreLimit = 206,
    /// <summary>
    ///天赋点不足
    /// </summary>
    [pbr::OriginalName("EC_HERO_TALENTPOINT_LIMIT")] EcHeroTalentpointLimit = 208,
    /// <summary>
    ///前置天赋没学会
    /// </summary>
    [pbr::OriginalName("EC_HERO_TALENTPRE_LIMIT")] EcHeroTalentpreLimit = 209,
    /// <summary>
    ///天赋已经学会
    /// </summary>
    [pbr::OriginalName("EC_HERO_TALENT_HASLEARN")] EcHeroTalentHaslearn = 210,
    /// <summary>
    ///英雄任务已经完成
    /// </summary>
    [pbr::OriginalName("EC_HERO_MISSION_HASFINISH")] EcHeroMissionHasfinish = 211,
    /// <summary>
    ///战斗相关错误码 300
    /// </summary>
    [pbr::OriginalName("EC_SWEEP_STARLIMIT")] EcSweepStarlimit = 300,
    /// <summary>
    ///扫荡次数限制
    /// </summary>
    [pbr::OriginalName("EC_SWEEP_COUNTLIMIT")] EcSweepCountlimit = 301,
    /// <summary>
    ///道具相关错误码 400
    /// </summary>
    [pbr::OriginalName("EC_RAFFLE_COUNTLIMIT")] EcRaffleCountlimit = 400,
  }

  /// <summary>
  ///道具类型
  /// </summary>
  public enum ItemTypeEnum {
    /// <summary>
    ///通用货币
    /// </summary>
    [pbr::OriginalName("ItemType_Money")] ItemTypeMoney = 0,
    /// <summary>
    ///卡牌
    /// </summary>
    [pbr::OriginalName("ItemType_Card")] ItemTypeCard = 1,
    /// <summary>
    ///卡牌碎片
    /// </summary>
    [pbr::OriginalName("ItemType_CardDebris")] ItemTypeCardDebris = 2,
    /// <summary>
    ///养成道具
    /// </summary>
    [pbr::OriginalName("ItemType_Develop")] ItemTypeDevelop = 3,
    /// <summary>
    ///模拟经营道具
    /// </summary>
    [pbr::OriginalName("ItemType_Manage")] ItemTypeManage = 4,
    /// <summary>
    ///礼包
    /// </summary>
    [pbr::OriginalName("ItemType_Box")] ItemTypeBox = 5,
    /// <summary>
    ///经验包
    /// </summary>
    [pbr::OriginalName("ItemType_HeroExp")] ItemTypeHeroExp = 6,
    /// <summary>
    ///抽奖券
    /// </summary>
    [pbr::OriginalName("ItemType_Raffle")] ItemTypeRaffle = 7,
    /// <summary>
    ///体力包
    /// </summary>
    [pbr::OriginalName("ItemType_AC")] ItemTypeAc = 8,
  }

  /// <summary>
  ///装备部位类型(与前端ChangeType相对应，可以考虑用一个)
  /// </summary>
  public enum EquipTypeEnum {
    /// <summary>
    ///无
    /// </summary>
    [pbr::OriginalName("Equip_None")] EquipNone = 0,
    /// <summary>
    ///头
    /// </summary>
    [pbr::OriginalName("EquipHead")] EquipHead = 1,
    /// <summary>
    ///衣服
    /// </summary>
    [pbr::OriginalName("EquipClothes")] EquipClothes = 2,
    /// <summary>
    ///武器
    /// </summary>
    [pbr::OriginalName("EquipWeapon")] EquipWeapon = 3,
    /// <summary>
    ///翅膀
    /// </summary>
    [pbr::OriginalName("EquipWing")] EquipWing = 4,
    /// <summary>
    ///坐骑
    /// </summary>
    [pbr::OriginalName("EquipRide")] EquipRide = 5,
    /// <summary>
    ///脸
    /// </summary>
    [pbr::OriginalName("EquipFace")] EquipFace = 6,
  }

  /// <summary>
  ///道具获得途径
  /// </summary>
  public enum ResourceSrcEnum {
    /// <summary>
    ///GM命令
    /// </summary>
    [pbr::OriginalName("Src_GM")] SrcGm = 0,
    /// <summary>
    ///杀怪
    /// </summary>
    [pbr::OriginalName("Src_PVE")] SrcPve = 1,
    /// <summary>
    ///击杀Boss
    /// </summary>
    [pbr::OriginalName("Src_PVB")] SrcPvb = 2,
    /// <summary>
    ///使用礼券
    /// </summary>
    [pbr::OriginalName("Src_Gift")] SrcGift = 4,
    /// <summary>
    ///采集
    /// </summary>
    [pbr::OriginalName("Src_Gather")] SrcGather = 5,
    /// <summary>
    ///任务奖励
    /// </summary>
    [pbr::OriginalName("Src_Task")] SrcTask = 7,
    /// <summary>
    ///开宝箱
    /// </summary>
    [pbr::OriginalName("Src_OpenBox")] SrcOpenBox = 8,
    /// <summary>
    ///升级
    /// </summary>
    [pbr::OriginalName("Src_LevelUp")] SrcLevelUp = 9,
    /// <summary>
    ///邮件
    /// </summary>
    [pbr::OriginalName("Src_Mail")] SrcMail = 10,
    /// <summary>
    ///关卡
    /// </summary>
    [pbr::OriginalName("Src_Fight")] SrcFight = 11,
    /// <summary>
    ///章节领奖
    /// </summary>
    [pbr::OriginalName("Src_ChapterReward")] SrcChapterReward = 12,
    /// <summary>
    ///英雄天赋奖励
    /// </summary>
    [pbr::OriginalName("Src_TalentReward")] SrcTalentReward = 13,
    /// <summary>
    ///抽卡
    /// </summary>
    [pbr::OriginalName("Src_Raffle")] SrcRaffle = 14,
    /// <summary>
    ///英雄分解
    /// </summary>
    [pbr::OriginalName("Src_HeroDecompose")] SrcHeroDecompose = 15,
    /// <summary>
    ///快捷购买
    /// </summary>
    [pbr::OriginalName("Src_QuickBuy")] SrcQuickBuy = 16,
    /// <summary>
    ///商城
    /// </summary>
    [pbr::OriginalName("Src_Store")] SrcStore = 17,
    /// <summary>
    ///道具使用
    /// </summary>
    [pbr::OriginalName("Src_ItemUse")] SrcItemUse = 18,
    /// <summary>
    ///功能购买
    /// </summary>
    [pbr::OriginalName("Src_FuncBuy")] SrcFuncBuy = 19,
    /// <summary>
    ///体力自然恢复
    /// </summary>
    [pbr::OriginalName("Src_AcRecover")] SrcAcRecover = 20,
  }

  /// <summary>
  ///道具消耗
  /// </summary>
  public enum ResourceDecEnum {
    /// <summary>
    ///GM
    /// </summary>
    [pbr::OriginalName("Dec_GM")] DecGm = 0,
    /// <summary>
    ///购买商店商品
    /// </summary>
    [pbr::OriginalName("Dec_BuyShopProduct")] DecBuyShopProduct = 3,
    /// <summary>
    ///商店商品刷新
    /// </summary>
    [pbr::OriginalName("Dec_ShopProductRef")] DecShopProductRef = 4,
    /// <summary>
    ///英雄升级
    /// </summary>
    [pbr::OriginalName("Dec_HeroLevelUp")] DecHeroLevelUp = 5,
    /// <summary>
    ///英雄升星
    /// </summary>
    [pbr::OriginalName("Dec_HeroStarUp")] DecHeroStarUp = 6,
    /// <summary>
    ///英雄进阶
    /// </summary>
    [pbr::OriginalName("Dec_HeroGradeUp")] DecHeroGradeUp = 7,
    /// <summary>
    ///战斗扫荡
    /// </summary>
    [pbr::OriginalName("Dec_FightSweep")] DecFightSweep = 8,
    /// <summary>
    ///编队栏位开启
    /// </summary>
    [pbr::OriginalName("Dec_TeamOpen")] DecTeamOpen = 9,
    /// <summary>
    ///抽卡[图片]
    /// </summary>
    [pbr::OriginalName("Dec_Raffle")] DecRaffle = 10,
    /// <summary>
    ///快捷购买
    /// </summary>
    [pbr::OriginalName("Dec_QuickBuy")] DecQuickBuy = 11,
    /// <summary>
    ///商城
    /// </summary>
    [pbr::OriginalName("Dec_Store")] DecStore = 12,
    /// <summary>
    ///角色技能升级
    /// </summary>
    [pbr::OriginalName("Dec_RoleSkill")] DecRoleSkill = 13,
    /// <summary>
    ///道具使用
    /// </summary>
    [pbr::OriginalName("Dec_ItemUse")] DecItemUse = 14,
    /// <summary>
    ///购买体力
    /// </summary>
    [pbr::OriginalName("Dec_BuyAc")] DecBuyAc = 15,
    /// <summary>
    ///次数组
    /// </summary>
    [pbr::OriginalName("Dec_CountGroup")] DecCountGroup = 16,
    /// <summary>
    ///英雄天赋学习
    /// </summary>
    [pbr::OriginalName("Dec_HeroTalent")] DecHeroTalent = 17,
  }

  /// <summary>
  ///资源类型
  /// </summary>
  public enum MoneyTypeEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("MoneyNone")] MoneyNone = 0,
    /// <summary>
    ///金币
    /// </summary>
    [pbr::OriginalName("MoneyGold")] MoneyGold = 1,
    /// <summary>
    ///真钻
    /// </summary>
    [pbr::OriginalName("MoneyDianmond")] MoneyDianmond = 2,
    /// <summary>
    ///绑钻
    /// </summary>
    [pbr::OriginalName("MoneyBindDianmond")] MoneyBindDianmond = 3,
    /// <summary>
    ///体力
    /// </summary>
    [pbr::OriginalName("MoneyAC")] MoneyAc = 5,
    /// <summary>
    ///竞技场货币
    /// </summary>
    [pbr::OriginalName("MoneyArena")] MoneyArena = 6,
    /// <summary>
    ///情报
    /// </summary>
    [pbr::OriginalName("MoneyIntelligence")] MoneyIntelligence = 7,
    /// <summary>
    ///抽奖代币
    /// </summary>
    [pbr::OriginalName("MoneyRaffle")] MoneyRaffle = 8,
    /// <summary>
    ///技能点
    /// </summary>
    [pbr::OriginalName("MoneySkillPoint")] MoneySkillPoint = 9,
    /// <summary>
    ///最大体力
    /// </summary>
    [pbr::OriginalName("MoneyMaxAC")] MoneyMaxAc = 10,
  }

  /// <summary>
  ///商店刷新规则
  /// </summary>
  public enum ShopRefRuleEnum {
    /// <summary>
    ///默认不生效，占位用
    /// </summary>
    [pbr::OriginalName("RefRule_Default")] RefRuleDefault = 0,
    /// <summary>
    ///随机
    /// </summary>
    [pbr::OriginalName("RefRule_Rand")] RefRuleRand = 1,
    /// <summary>
    ///随机不重复
    /// </summary>
    [pbr::OriginalName("RefRule_RandNotRepeated")] RefRuleRandNotRepeated = 2,
    /// <summary>
    ///顺序
    /// </summary>
    [pbr::OriginalName("RefRule_Sequence")] RefRuleSequence = 3,
  }

  /// <summary>
  ///效果类型
  /// </summary>
  public enum EffectTypeEnum {
    /// <summary>
    ///伤害
    /// </summary>
    [pbr::OriginalName("ET_Hurt")] EtHurt = 0,
    /// <summary>
    ///中毒
    /// </summary>
    [pbr::OriginalName("ET_Poison")] EtPoison = 1,
    /// <summary>
    ///治疗
    /// </summary>
    [pbr::OriginalName("ET_Cure")] EtCure = 2,
    /// <summary>
    ///金身
    /// </summary>
    [pbr::OriginalName("ET_Gold")] EtGold = 3,
    /// <summary>
    ///沉默
    /// </summary>
    [pbr::OriginalName("ET_Silence")] EtSilence = 4,
    /// <summary>
    ///眩晕
    /// </summary>
    [pbr::OriginalName("ET_Dizzy")] EtDizzy = 5,
    /// <summary>
    ///沉睡
    /// </summary>
    [pbr::OriginalName("ET_Sleep")] EtSleep = 6,
    /// <summary>
    ///技能回合改变
    /// </summary>
    [pbr::OriginalName("ET_SkillCd")] EtSkillCd = 7,
    /// <summary>
    ///颠覆，吸取敌方有益buff
    /// </summary>
    [pbr::OriginalName("ET_Subversive")] EtSubversive = 8,
    /// <summary>
    ///流血，百分比掉血
    /// </summary>
    [pbr::OriginalName("ET_Bleed")] EtBleed = 10,
    /// <summary>
    ///反击伤害
    /// </summary>
    [pbr::OriginalName("ET_Counter")] EtCounter = 22,
    /// <summary>
    ///吸血
    /// </summary>
    [pbr::OriginalName("ET_Leech")] EtLeech = 23,
    /// <summary>
    ///恢复
    /// </summary>
    [pbr::OriginalName("ET_Recover")] EtRecover = 24,
    /// <summary>
    ///驱散
    /// </summary>
    [pbr::OriginalName("ET_ChangeBuffRound1")] EtChangeBuffRound1 = 26,
    /// <summary>
    ///净化
    /// </summary>
    [pbr::OriginalName("ET_ChangeBuffRound2")] EtChangeBuffRound2 = 27,
    /// <summary>
    ///负面效果延长
    /// </summary>
    [pbr::OriginalName("ET_ChangeBuffRound3")] EtChangeBuffRound3 = 28,
    /// <summary>
    ///正面效果盐城
    /// </summary>
    [pbr::OriginalName("ET_ChangeBuffRound4")] EtChangeBuffRound4 = 29,
    /// <summary>
    ///技能冷却延长
    /// </summary>
    [pbr::OriginalName("ET_ChangeSkillRound1")] EtChangeSkillRound1 = 30,
    /// <summary>
    ///技能冷却缩减
    /// </summary>
    [pbr::OriginalName("ET_ChangeSkillRound2")] EtChangeSkillRound2 = 31,
    /// <summary>
    ///必中（buff持有者必然命中被攻击者）
    /// </summary>
    [pbr::OriginalName("ET_MustHit")] EtMustHit = 32,
    /// <summary>
    ///锁定不能闪避（攻击者必然命中buff持有者）
    /// </summary>
    [pbr::OriginalName("ET_UnMiss")] EtUnMiss = 33,
    /// <summary>
    ///免疫，目标免疫所有负面状态
    /// </summary>
    [pbr::OriginalName("ET_Immune")] EtImmune = 34,
    /// <summary>
    ///嘲讽，目标成为敌方首选攻击目标
    /// </summary>
    [pbr::OriginalName("ET_Taunt")] EtTaunt = 35,
    /// <summary>
    ///多次行动
    /// </summary>
    [pbr::OriginalName("ET_MultiAction")] EtMultiAction = 36,
    /// <summary>
    ///混乱
    /// </summary>
    [pbr::OriginalName("ET_Chaos")] EtChaos = 37,
    /// <summary>
    ///禁止被动
    /// </summary>
    [pbr::OriginalName("ET_ForbidPASV")] EtForbidPasv = 38,
    /// <summary>
    ///护盾值
    /// </summary>
    [pbr::OriginalName("ET_ShieldUp")] EtShieldUp = 100,
    /// <summary>
    ///增加血量上限
    /// </summary>
    [pbr::OriginalName("ET_MaxHpUp")] EtMaxHpUp = 101,
    /// <summary>
    ///降低血量上限
    /// </summary>
    [pbr::OriginalName("ET_MaxHpDown")] EtMaxHpDown = 102,
    /// <summary>
    ///增加攻击
    /// </summary>
    [pbr::OriginalName("ET_AtkUp")] EtAtkUp = 103,
    /// <summary>
    ///降低攻击
    /// </summary>
    [pbr::OriginalName("ET_AtkDown")] EtAtkDown = 104,
    /// <summary>
    ///增加防御
    /// </summary>
    [pbr::OriginalName("ET_DefUp")] EtDefUp = 105,
    /// <summary>
    ///降低防御
    /// </summary>
    [pbr::OriginalName("ET_DefDown")] EtDefDown = 106,
    /// <summary>
    ///增加闪避
    /// </summary>
    [pbr::OriginalName("ET_DodUp")] EtDodUp = 107,
    /// <summary>
    ///降低闪避
    /// </summary>
    [pbr::OriginalName("ET_DodDown")] EtDodDown = 108,
    /// <summary>
    ///增加暴击
    /// </summary>
    [pbr::OriginalName("ET_CritUp")] EtCritUp = 109,
    /// <summary>
    ///降低暴击
    /// </summary>
    [pbr::OriginalName("ET_CritDown")] EtCritDown = 110,
    /// <summary>
    ///增加暴击伤害
    /// </summary>
    [pbr::OriginalName("ET_CritDamageUp")] EtCritDamageUp = 111,
    /// <summary>
    ///降低暴击伤害
    /// </summary>
    [pbr::OriginalName("ET_CritDamageDown")] EtCritDamageDown = 112,
    /// <summary>
    ///增加暴击防御
    /// </summary>
    [pbr::OriginalName("ET_CritDefUp")] EtCritDefUp = 113,
    /// <summary>
    ///降低暴击防御
    /// </summary>
    [pbr::OriginalName("ET_CritDefDown")] EtCritDefDown = 114,
    /// <summary>
    ///增加命中
    /// </summary>
    [pbr::OriginalName("ET_HitUp")] EtHitUp = 115,
    /// <summary>
    ///降低命中
    /// </summary>
    [pbr::OriginalName("ET_HitDown")] EtHitDown = 116,
  }

  /// <summary>
  ///属性定义，要保证连续，Num为总属性索引，程序用Num做逻辑
  /// </summary>
  public enum EPROP {
    /// <summary>
    ///空值
    /// </summary>
    [pbr::OriginalName("PROP_NONE")] PropNone = 0,
    /// <summary>
    ///当前血量
    /// </summary>
    [pbr::OriginalName("PROP_HP")] PropHp = 1,
    /// <summary>
    ///最大血量
    /// </summary>
    [pbr::OriginalName("PROP_MAXHP")] PropMaxhp = 2,
    /// <summary>
    ///攻击
    /// </summary>
    [pbr::OriginalName("PROP_ATK")] PropAtk = 3,
    /// <summary>
    ///防御
    /// </summary>
    [pbr::OriginalName("PROP_DEF")] PropDef = 4,
    /// <summary>
    ///闪避
    /// </summary>
    [pbr::OriginalName("PROP_DOD")] PropDod = 5,
    /// <summary>
    ///暴击
    /// </summary>
    [pbr::OriginalName("PROP_CRIT")] PropCrit = 6,
    /// <summary>
    ///护盾
    /// </summary>
    [pbr::OriginalName("PROP_SHIELD")] PropShield = 7,
    /// <summary>
    ///命中
    /// </summary>
    [pbr::OriginalName("PROP_HIT")] PropHit = 8,
    /// <summary>
    ///暴击伤害
    /// </summary>
    [pbr::OriginalName("PROP_CRITDAMAGE")] PropCritdamage = 9,
    /// <summary>
    ///暴击防御
    /// </summary>
    [pbr::OriginalName("PROP_CRITDEF")] PropCritdef = 10,
    /// <summary>
    ///属性数量
    /// </summary>
    [pbr::OriginalName("PROP_Num")] PropNum = 11,
  }

  /// <summary>
  ///单位类型
  /// </summary>
  public enum EntityTypeEnum {
    /// <summary>
    ///英雄
    /// </summary>
    [pbr::OriginalName("ET_Hero")] EtHero = 0,
    /// <summary>
    ///怪物
    /// </summary>
    [pbr::OriginalName("ET_Monster")] EtMonster = 1,
    /// <summary>
    ///玩家
    /// </summary>
    [pbr::OriginalName("ET_Player")] EtPlayer = 2,
  }

  /// <summary>
  ///技能类型
  /// </summary>
  public enum SkillTypeEnum {
    /// <summary>
    ///默认值
    /// </summary>
    [pbr::OriginalName("SkillType_None")] SkillTypeNone = 0,
    /// <summary>
    ///普通攻击
    /// </summary>
    [pbr::OriginalName("SkillType_Normal")] SkillTypeNormal = 1,
    /// <summary>
    ///大招
    /// </summary>
    [pbr::OriginalName("SkillType_Unique")] SkillTypeUnique = 2,
    /// <summary>
    ///被动技能
    /// </summary>
    [pbr::OriginalName("SkillType_PASV")] SkillTypePasv = 3,
    /// <summary>
    ///玩家技能
    /// </summary>
    [pbr::OriginalName("SkillType_Player")] SkillTypePlayer = 4,
  }

  /// <summary>
  ///技能区域
  /// </summary>
  public enum SkillAreaEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("SkillArea_Invalid")] SkillAreaInvalid = 0,
    /// <summary>
    ///全部
    /// </summary>
    [pbr::OriginalName("SkillArea_All")] SkillAreaAll = 1,
    /// <summary>
    ///前
    /// </summary>
    [pbr::OriginalName("SkillArea_Front")] SkillAreaFront = 2,
    /// <summary>
    ///后
    /// </summary>
    [pbr::OriginalName("SkillArea_Behind")] SkillAreaBehind = 3,
  }

  /// <summary>
  ///技能阵营
  /// </summary>
  public enum SkillCampEnum {
    /// <summary>
    ///敌方
    /// </summary>
    [pbr::OriginalName("SkillCamp_Enemy")] SkillCampEnemy = 0,
    /// <summary>
    ///友方
    /// </summary>
    [pbr::OriginalName("SkillCamp_Friend")] SkillCampFriend = 1,
    /// <summary>
    ///全部（场地技能）
    /// </summary>
    [pbr::OriginalName("SkillCamp_All")] SkillCampAll = 2,
  }

  /// <summary>
  ///技能目标类型
  /// </summary>
  public enum TargetTypeEnum {
    /// <summary>
    ///单个
    /// </summary>
    [pbr::OriginalName("SkillTypeSingle")] SkillTypeSingle = 0,
    /// <summary>
    ///全体
    /// </summary>
    [pbr::OriginalName("SkillTypeAll")] SkillTypeAll = 1,
    /// <summary>
    ///随机
    /// </summary>
    [pbr::OriginalName("SkillTypeRand")] SkillTypeRand = 2,
    /// <summary>
    ///血量最少
    /// </summary>
    [pbr::OriginalName("SkillTypeMinHp")] SkillTypeMinHp = 3,
    /// <summary>
    ///自身
    /// </summary>
    [pbr::OriginalName("SkillTypeSelf")] SkillTypeSelf = 4,
  }

  /// <summary>
  ///战斗条件枚举值
  /// </summary>
  public enum FightConditionEnum {
    /// <summary>
    ///敌方英雄全灭
    /// </summary>
    [pbr::OriginalName("FightCondition_EnemyAllDie")] FightConditionEnemyAllDie = 0,
    /// <summary>
    ///敌方某个英雄死亡
    /// </summary>
    [pbr::OriginalName("FightCondition_EnemyHeroDie")] FightConditionEnemyHeroDie = 1,
    /// <summary>
    ///己方存活英雄数量
    /// </summary>
    [pbr::OriginalName("FightCondition_FirendAliveCount")] FightConditionFirendAliveCount = 2,
    /// <summary>
    ///己方某个英雄死亡
    /// </summary>
    [pbr::OriginalName("FightCondition_FriendHeroDie")] FightConditionFriendHeroDie = 3,
    /// <summary>
    ///己方英雄全灭
    /// </summary>
    [pbr::OriginalName("FightCondition_FriendAllDie")] FightConditionFriendAllDie = 4,
  }

  /// <summary>
  ///英雄任务目标类型
  /// </summary>
  public enum HeroMissionObjEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("HeroObj_Invalid")] HeroObjInvalid = 0,
    /// <summary>
    ///升级
    /// </summary>
    [pbr::OriginalName("HeroObj_Level")] HeroObjLevel = 1,
    /// <summary>
    ///战斗
    /// </summary>
    [pbr::OriginalName("HeroObj_Win")] HeroObjWin = 2,
    /// <summary>
    ///进阶
    /// </summary>
    [pbr::OriginalName("HeroObj_Grade")] HeroObjGrade = 3,
    /// <summary>
    ///升星
    /// </summary>
    [pbr::OriginalName("HeroObj_Star")] HeroObjStar = 4,
    /// <summary>
    ///互动
    /// </summary>
    [pbr::OriginalName("HeroObj_LinkUp")] HeroObjLinkUp = 5,
  }

  /// <summary>
  ///英雄天赋奖励类型
  /// </summary>
  public enum HeroTalentRewardEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("TalentReward_Invalid")] TalentRewardInvalid = 0,
    /// <summary>
    ///属性
    /// </summary>
    [pbr::OriginalName("TalentReward_Prop")] TalentRewardProp = 1,
    /// <summary>
    ///BUFF
    /// </summary>
    [pbr::OriginalName("TalentReward_BUFF")] TalentRewardBuff = 2,
    /// <summary>
    ///立绘
    /// </summary>
    [pbr::OriginalName("TalentReward_ICon")] TalentRewardIcon = 3,
    /// <summary>
    ///交互解锁
    /// </summary>
    [pbr::OriginalName("TalentReward_LinkUp")] TalentRewardLinkUp = 4,
    /// <summary>
    ///货币奖励
    /// </summary>
    [pbr::OriginalName("TalentReward_Resource")] TalentRewardResource = 5,
  }

  /// <summary>
  ///抽卡类型枚举值
  /// </summary>
  public enum RaffleTypeEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("RaffleType_Invalid")] RaffleTypeInvalid = 0,
    /// <summary>
    ///英雄
    /// </summary>
    [pbr::OriginalName("RaffleType_Hero")] RaffleTypeHero = 1,
    /// <summary>
    ///家具
    /// </summary>
    [pbr::OriginalName("RaffleType_Furniture")] RaffleTypeFurniture = 2,
  }

  /// <summary>
  ///英雄质量枚举值
  /// </summary>
  public enum HeroQualityEnum {
    /// <summary>
    ///SSR
    /// </summary>
    [pbr::OriginalName("HeroQuality_SSR")] HeroQualitySsr = 0,
    /// <summary>
    ///SR
    /// </summary>
    [pbr::OriginalName("HeroQuality_SR")] HeroQualitySr = 1,
    /// <summary>
    ///R
    /// </summary>
    [pbr::OriginalName("HeroQuality_R")] HeroQualityR = 2,
  }

  /// <summary>
  ///关卡难度枚举值
  /// </summary>
  public enum DifficultyTypeEnum {
    /// <summary>
    ///普通
    /// </summary>
    [pbr::OriginalName("Difficulty_Normal")] DifficultyNormal = 0,
    /// <summary>
    ///困难
    /// </summary>
    [pbr::OriginalName("Difficulty_Hard")] DifficultyHard = 1,
  }

  /// <summary>
  ///购买购买类型
  /// </summary>
  public enum FuncPurcType {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("FuncPurc_Invalid")] FuncPurcInvalid = 0,
    /// <summary>
    ///购买体力点
    /// </summary>
    [pbr::OriginalName("FuncPurc_AC")] FuncPurcAc = 1,
    /// <summary>
    ///竞技场次数
    /// </summary>
    [pbr::OriginalName("FuncPurc_Arena")] FuncPurcArena = 2,
  }

  /// <summary>
  ///buff类型
  /// </summary>
  public enum BuffTypeEnum {
    /// <summary>
    ///无效
    /// </summary>
    [pbr::OriginalName("BuffType_Invalid")] BuffTypeInvalid = 0,
    /// <summary>
    ///正面
    /// </summary>
    [pbr::OriginalName("BuffType_Buff")] BuffTypeBuff = 1,
    /// <summary>
    ///负面
    /// </summary>
    [pbr::OriginalName("BuffType_Debuff")] BuffTypeDebuff = 2,
    /// <summary>
    ///中立
    /// </summary>
    [pbr::OriginalName("BuffType_Neutrality")] BuffTypeNeutrality = 3,
  }

  #endregion

}

#endregion Designer generated code
