// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageId.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from MessageId.proto</summary>
  public static partial class MessageIdReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageId.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageIdReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9NZXNzYWdlSWQucHJvdG8SCHByb3RvY29sKqMtCglNZXNzYWdlSWQSDQoJ",
            "TVNHX0JFR0lOEAASGAoTTVNHSURfQzJTX0VudGVyR2FtZRDoBxIbChZNU0dJ",
            "RF9DMlNfQ3JlYXRlUGxheWVyEOkHEhQKD01TR0lEX0MyU19NYXRjaBDqBxIc",
            "ChdNU0dJRF9DMlNfQ2hhbmdlRmFzaGlvbhDrBxIaChVNU0dJRF9DMlNfQ2Fu",
            "Y2VsTWF0Y2gQ7AcSFwoSTVNHSURfQzJTX1JlYWRNYWlsEO0HEhoKFU1TR0lE",
            "X0MyU19SZWNlaXZlTWFpbBDuBxIWChFNU0dJRF9DMlNfRGVsTWFpbBDvBxIc",
            "ChdNU0dJRF9DMlNfQ2hlY2tSb2xlTmFtZRDwBxIbChZNU0dJRF9DMlNfQ29u",
            "dGludWVHYW1lEPEHEhIKDU1TR0lEX0MyU19QYXkQ8gcSGwoWTVNHSURfQzJT",
            "X1JlY29ubmVjdGlvbhDzBxIbChZNU0dJRF9DMlNfSW52aXRlRnJpZW50EPQH",
            "EhoKFU1TR0lEX0MyU19SZXFTaG9wVGltZRD1BxIZChRNU0dJRF9DMlNfUmVx",
            "U2hvcEJ1eRD2BxIXChJNU0dJRF9DMlNfUGF5T3JkZXIQ9wcSGgoVTVNHSURf",
            "QzJTX1BheUZpbmlzaGVkEPgHEhkKFE1TR0lEX0MyU19DaGFuZ2VOYW1lEPkH",
            "EhoKFU1TR0lEX0MyU19DaGFuZ2VUaXRsZRD6BxIeChlNU0dJRF9DMlNfQ2hh",
            "bmdlU2lnbmF0dXJlEPsHEhkKFE1TR0lEX0MyU19RdWVyeU9yZGVyEPwHEhkK",
            "FE1TR0lEX0MyU19DcmVhdGVUZWFtEIYIEhgKE01TR0lEX0MyU19FbnRlclRl",
            "YW0QhwgSFwoSTVNHSURfQzJTX0V4aXRUZWFtEIgIEhkKFE1TR0lEX0MyU19C",
            "dXlUYWdDYXJkEJAIEh4KGU1TR0lEX0MyU19TZXRUYWdDYXJkU3RhdGUQkQgS",
            "HQoYTVNHSURfQzJTX1JlcXVlc3RMb3R0ZXJ5EJIIEh0KGE1TR0lEX0MyU19C",
            "dXlMb3R0ZXJ5Q29pbhCTCBIbChZNU0dJRF9DMlNfTmdnQnV5VmVyaWZ5EJQI",
            "EhsKFk1TR0lEX0MyU19SZXNldENvbm5lY3QQzg8SGAoTTVNHSURfQzJTX0hl",
            "YXJ0QmVhdBDPDxIZChRNU0dJRF9TMkNfUGxheWVySW5mbxDQDxIbChZNU0dJ",
            "RF9TMkNfQ3JlYXRlUGxheWVyENEPEhoKFU1TR0lEX1MyQ19NYXRjaFJlc3Vs",
            "dBDSDxIZChRNU0dJRF9TMkNfVGFyZ2V0SW5mbxDTDxIcChdNU0dJRF9TMkNf",
            "Q2hhbmdlRmFzaGlvbhDUDxIYChNNU0dJRF9TMkNfUGFydHNJbmZvENUPEhsK",
            "Fk1TR0lEX1MyQ19Mb2FkTWFpbEluZm8Q1g8SFwoSTVNHSURfUzJDX1JlYWRN",
            "YWlsENcPEhYKEU1TR0lEX1MyQ19SZWNlaXZlENgPEhYKEU1TR0lEX1MyQ19E",
            "ZWxNYWlsENkPEh0KGE1TR0lEX1MyQ19PcGVuQmF0dGxlUGFzcxDaDxIeChlN",
            "U0dJRF9TMkNfQ2xvc2VCYXR0bGVQYXNzENsPEhsKFk1TR0lEX1MyQ19CYXR0",
            "bGVQYXNzTHYQ3A8SHAoXTVNHSURfUzJDX0JhdHRsZVBhc3NQYXkQ3Q8SHAoX",
            "TVNHSURfUzJDX0NoZWNrUm9sZU5hbWUQ3g8SGgoVTVNHSURfUzJDX0NhbmNl",
            "bE1hdGNoEN8PEhQKD01TR0lEX1MyQ19NYXRjaBDgDxISCg1NU0dJRF9TMkNf",
            "UGF5EOEPEhsKFk1TR0lEX1MyQ19JbnZpdGVSZXN1bHQQ4g8SGwoWTVNHSURf",
            "UzJDX0ludml0ZU5vdGljZRDjDxIWChFNU0dJRF9TMkNfQWRkSXRlbRDkDxIa",
            "ChVNU0dJRF9TMkNfQ2hhbmdlTW9uZXkQ5Q8SHAoXTVNHSURfUzJDX1Nob3BS",
            "ZWZOb3RpY2UQ5g8SGgoVTVNHSURfUzJDX1Nob3BSZWZUaW1lEOcPEhwKF01T",
            "R0lEX1MyQ19TaG9wQnV5UmVzdWx0EOgPEhoKFU1TR0lEX1MyQ19QYXlGaW5p",
            "c2hlZBDpDxIZChRNU0dJRF9TMkNfQ2hhbmdlTmFtZRDqDxIaChVNU0dJRF9T",
            "MkNfQ2hhbmdlVGl0bGUQ6w8SHgoZTVNHSURfUzJDX0NoYW5nZVNpZ25hdHVy",
            "ZRDsDxIXChJNU0dJRF9TMkNfVGVhbUluZm8Q7g8SIgodTVNHSURfUzJDX0Vu",
            "dGVyVGVhbV9Ccm9hZGNhc3QQ7w8SIQocTVNHSURfUzJDX0V4aXRUZWFtX0Jy",
            "b2FkY2FzdBDwDxIaChVNU0dJRF9TMkNfVGVhbV9SZXN1bHQQ8Q8SHQoYTVNH",
            "SURfUzJDX0J1eVRhZ0NhcmRfUmV0EPgPEhwKF01TR0lEX1MyQ19DaGFuZ2VU",
            "YWdDYXJkEPkPEhsKFk1TR0lEX1MyQ19UYWdDYXJkU3RhdGUQ+g8SHgoZTVNH",
            "SURfUzJDX1Jlc3BvbnNlTG90dGVyeRD7DxIgChtNU0dJRF9TMkNfQ2hhbmdl",
            "TG90dGVyeUNvaW4Q/A8SIAobTVNHSURfUzJDX0J1eUxvdHRlcnlDb2luUmV0",
            "EP0PEhsKFk1TR0lEX1MyQ19OZ2dCdXlWZXJpZnkQ/g8SHAoXTVNHSURfUzJD",
            "X0ZpcnN0UmVjaGFyZ2UQ/w8SIAobTVNHSURfUzJDX0ZpcnN0UmVjaGFyZ0dv",
            "b2RzEIAQEhsKFk1TR0lEX1MyQ19SZXNldENvbm5lY3QQtRcSFQoQTVNHSURf",
            "UzJDX1JlbG9hZBC2FxIYChNNU0dJRF9TMkNfSGVhcnRCZWF0ELcXEhkKFE1T",
            "R0lEX0MyTF9FbnRlclNjZW5lELgXEh4KGU1TR0lEX0MyTF9Mb2FkTWFwRmlu",
            "aXNoZWQQuRcSFwoSTVNHSURfQzJMX1N5bmNNb3ZlELoXEhYKEU1TR0lEX0My",
            "TF9NZWV0aW5nELsXEhgKE01TR0lEX0MyTF9DaGVja0RlYWQQvBcSEwoOTVNH",
            "SURfQzJMX0NoYXQQvRcSEwoOTVNHSURfQzJMX1ZvdGUQvhcSGgoVTVNHSURf",
            "QzJMX1B1enpsZVN0YXJ0EL8XEhsKFk1TR0lEX0MyTF9QdXp6bGVGaW5pc2gQ",
            "wBcSGwoWTVNHSURfQzJMX1B1enpsZUZhaWxlZBDBFxIcChdNU0dJRF9DMkxf",
            "RGVzdHJveVB1enpsZRDCFxIZChRNU0dJRF9DMkxfUGlja3VwSXRlbRDDFxIW",
            "ChFNU0dJRF9DMkxfVXNlSXRlbRDEFxITCg5NU0dJRF9DMkxfSnVtcBDFFxIV",
            "ChBNU0dJRF9DMkxfQXR0YWNrEMYXEhYKEU1TR0lEX0MyTF9Vc2VMaWZ0EMcX",
            "EhkKFE1TR0lEX0MyTF9Vc2VNb25pdG9yEMgXEhwKF01TR0lEX0MyTF9DYW5j",
            "ZWxNb25pdG9yEMkXEhQKD01TR0lEX0MyTF9Wb2ljZRDKFxIYChNNU0dJRF9D",
            "MkxfUGlja1VwS2V5EMsXEhoKFU1TR0lEX0MyTF9NZWV0aW5nTW92ZRDMFxIX",
            "ChJNU0dJRF9DMkxfRW50ZXJCb3gQzRcSFwoSTVNHSURfQzJMX0xlYXZlQm94",
            "EM4XEhkKFE1TR0lEX0MyTF9EZXN0cm95Qm94EM8XEhgKE01TR0lEX0MyTF9S",
            "ZXBhaXJCb3gQ0BcSIAobTVNHSURfQzJMX1JlcGFpckJveF9TdWNjZWVkENEX",
            "Eh8KGk1TR0lEX0MyTF9SZXBhaXJCb3hfRmFpbGVkENIXEh8KGk1TR0lEX0My",
            "TF9BdHRhY2tfU3RpbGxsaWZlENYXEhcKEk1TR0lEX0MyTF9Vc2VTa2lsbBDg",
            "FxIZChRNU0dJRF9DMkxfVG9OZXh0Um9vbRDhFxIbChZNU0dJRF9DMkxfUmVj",
            "b25uZWN0aW9uEJ4fEhgKE01TR0lEX0MyTF9IZWFydEJlYXQQnx8SGQoUTVNH",
            "SURfTDJDX0VudGVyU2NlbmUQoB8SJAofTVNHSURfTDJDX1BsYXllcnNJbmZv",
            "X0Jyb2FkY2FzdBChHxIkCh9NU0dJRF9MMkNfV2FpdE1lZXRpbmdfQnJvYWRj",
            "YXN0EKIfEhUKEE1TR0lEX0wyQ19TZXRQb3MQox8SIQocTVNHSURfTDJDX1N5",
            "bmNNb3ZlX0Jyb2FkY2FzdBCkHxIWChFNU0dJRF9MMkNfTWVldGluZxClHxIY",
            "ChNNU0dJRF9MMkNfQ2hlY2tEZWFkEKYfEiAKG01TR0lEX0wyQ19NZWV0aW5n",
            "X0Jyb2FkY2FzdBCnHxIdChhNU0dJRF9MMkNfQ2hhdF9Ccm9hZGNhc3QQqR8S",
            "HQoYTVNHSURfTDJDX1ZvdGVfQnJvYWRjYXN0EKsfEiQKH01TR0lEX0wyQ19N",
            "ZWV0aW5nT3Zlcl9Ccm9hZGNhc3QQrB8SHgoZTVNHSURfTDJDX1ZvaWNlX0Jy",
            "b2FkY2FzdBCtHxIkCh9NU0dJRF9MMkNfUHV6emxlU3RhcnRfQnJvYWRjYXN0",
            "EK4fEiUKIE1TR0lEX0wyQ19QdXp6bGVGaW5pc2hfQnJvYWRjYXN0EK8fEiUK",
            "IE1TR0lEX0wyQ19QdXp6bGVGYWlsZWRfQnJvYWRjYXN0ELAfEiYKIU1TR0lE",
            "X0wyQ19EZXN0cm95UHV6emxlX0Jyb2FkY2FzdBCxHxIgChtNU0dJRF9MMkNf",
            "QWRkQnVmZl9Ccm9hZGNhc3QQtx8SIAobTVNHSURfTDJDX1JlbUJ1ZmZfQnJv",
            "YWRjYXN0ELgfEiMKHk1TR0lEX0wyQ19QaWNrdXBJdGVtX0Jyb2FkY2FzdBC5",
            "HxIgChtNU0dJRF9MMkNfVXNlSXRlbV9Ccm9hZGNhc3QQuh8SKQokTVNHSURf",
            "TDJDX0dhbWVTdGFydE5vdGljZXNfQnJvYWRjYXN0ELYfEiIKHU1TR0lEX0wy",
            "Q19HYW1lU3RhcnRfQnJvYWRjYXN0ELsfEiUKIE1TR0lEX0wyQ19HYW1lQ29u",
            "dGludWVfQnJvYWRjYXN0ELwfEiwKJ01TR0lEX0wyQ19HYW1lQ2xlYXJpbmdO",
            "b3RpY2VzX0Jyb2FkY2FzdBC9HxIlCiBNU0dJRF9MMkNfR2FtZUNsZWFyaW5n",
            "X0Jyb2FkY2FzdBC+HxIhChxNU0dJRF9MMkNfR2FtZU92ZXJfQnJvYWRjYXN0",
            "EL8fEh0KGE1TR0lEX0wyQ19KdW1wX0Jyb2FkY2FzdBDAHxIoCiNNU0dJRF9M",
            "MkNfQXR0cmlidXRlQ2hhbmdlX0Jyb2FkY2FzdBDBHxIVChBNU0dJRF9MMkNf",
            "QXR0YWNrEMIfEiIKHU1TR0lEX0wyQ19TeW5jU3RhdGVfQnJvYWRjYXN0EMMf",
            "EiAKG01TR0lEX0wyQ19Vc2VMaWZ0X0Jyb2FkY2FzdBDEHxIjCh5NU0dJRF9M",
            "MkNfVXNlTW9uaXRvcl9Ccm9hZGNhc3QQxR8SJgohTVNHSURfTDJDX0NhbmNl",
            "bE1vbml0b3JfQnJvYWRjYXN0EMYfEicKIk1TR0lEX0wyQ19DaGFuZ2VHYW1l",
            "VGltZV9Ccm9hZGNhc3QQxx8SIwoeTVNHSURfTDJDX0NyZWF0ZVRyYXBfQnJv",
            "YWRjYXN0EMgfEiQKH01TR0lEX0wyQ19EZXN0cm95VHJhcF9Ccm9hZGNhc3QQ",
            "yR8SHQoYTVNHSURfTDJDX0RlYWRfQnJvYWRjYXN0EMofEigKI01TR0lEX0wy",
            "Q19Mb2FkTWFwRmluaXNoZWRfQnJvYWRjYXN0EMsfEh4KGU1TR0lEX0wyQ19D",
            "b3JlUHV6emxlX09wZW4QzB8SIQocTVNHSURfTDJDX1RyYW5Sb29tX0Jyb2Fk",
            "Y2FzdBDNHxIeChlNU0dJRF9MMkNfSXRlbVN0YXRlVXBkYXRlEM4fEiAKG01T",
            "R0lEX0wyQ19LZXlEYXRhX0Jyb2FkY2FzdBDPHxIkCh9NU0dJRF9MMkNfTWVl",
            "dGluZ01vdmVfQnJvYWRjYXN0ENAfEiIKHU1TR0lEX0wyQ19HYW1lU3RhdGVf",
            "QnJvYWRjYXN0ENEfEiIKHU1TR0lEX0wyQ19HYW1lU3RhZ2VfQnJvYWRjYXN0",
            "ENIfEiEKHE1TR0lEX0wyQ19FbnRlckJveF9Ccm9hZGNhc3QQ0x8SIQocTVNH",
            "SURfTDJDX0xlYXZlQm94X0Jyb2FkY2FzdBDUHxIjCh5NU0dJRF9MMkNfRGVz",
            "dHJveUJveF9Ccm9hZGNhc3QQ1R8SIgodTVNHSURfTDJDX1JlcGFpckJveF9C",
            "cm9hZGNhc3QQ1h8SKgolTVNHSURfTDJDX1JlcGFpckJveF9TdWNjZWVkX0Jy",
            "b2FkY2FzdBDXHxIpCiRNU0dJRF9MMkNfUmVwYWlyQm94X0ZhaWxlZF9Ccm9h",
            "ZGNhc3QQ2B8SIgodTVNHSURfTDJDX0pvYkNoYW5nZV9Ccm9hZGNhc3QQ2R8S",
            "KQokTVNHSURfTDJDX0F0dGFja19TdGlsbGxpZmVfQnJvYWRjYXN0ENwfEiEK",
            "HE1TR0lEX0wyQ19Vc2VTa2lsbF9Ccm9hZGNhc3QQ5h8SIwoeTVNHSURfTDJD",
            "X1RvTmV4dFJvb21fQnJvYWRjYXN0EOcfEiAKG01TR0lEX0wyQ19Db25uZWN0",
            "aW9uSW52YWxpZBCFJxIbChZNU0dJRF9MMkNfUmVjb25uZWN0aW9uEIYnEhgK",
            "E01TR0lEX0wyQ19IZWFydEJlYXQQhycSEwoOTVNHSURfQzJBX0F1dGgQiCcS",
            "GAoTTVNHSURfQzJBX1N0ZWFtQXV0aBCJJxIZChRNU0dJRF9DMkFfV2VHYW1l",
            "QXV0aBCKJxITCg5NU0dJRF9BMkNfQXV0aBDwLhIbChZNU0dJRF9XMlNfUmVx",
            "dWVzdEVudGVyENg2EhoKFU1TR0lEX1cyU19QYXlGaW5pc2hlZBDZNhIWChFN",
            "U0dJRF9XMlNfQWRkSXRlbRDaNhIbChZNU0dJRF9XMlNfTmdnQnV5VmVyaWZ5",
            "ENs2EhsKFk1TR0lEX1MyV19SZXF1ZXN0RW50ZXIQzDoSFwoSTVNHSURfUzJX",
            "X1BheU9yZGVyEM06EhoKFU1TR0lEX1MyV19QYXlGaW5pc2hlZBDOOhIWChFN",
            "U0dJRF9TMldfQWRkSXRlbRDPOhIZChRNU0dJRF9TMldfUXVlcnlPcmRlchDQ",
            "OhIbChZNU0dJRF9TMldfTmdnQnV5VmVyaWZ5ENE6EhwKF01TR0lEX1MyR19B",
            "ZGRQbGF5ZXJJbmZvEMA+EhwKF01TR0lEX1MyR19EZWxQbGF5ZXJJbmZvEME+",
            "EhwKF01TR0lEX0cyU19QbGF5ZXJPZmZsaW5lELRCEhoKFU1TR0lEX0wyU19D",
            "cmVhdGVTY2VuZRCoRhIZChRNU0dJRF9MMlNfR2FtZVJlc3VsdBCpRhIZChRN",
            "U0dJRF9MMlNfUGxheWVyRGVhZBCqRhIaChVNU0dJRF9TMkxfQ3JlYXRlU2Nl",
            "bmUQnEoSGQoUTVNHSURfUzJMX0VudGVyU2NlbmUQnUoSFwoSTVNHSURfR01f",
            "QzJTX0xvZ2luEJBOEhcKEk1TR0lEX0dNX1MyQ19Mb2dpbhCRThIWChFNU0dJ",
            "RF9HTV9DMlNfTWFpbBCSThIYChNNU0dJRF9HTV9TMkNfUmVzdWx0EJNOEhUK",
            "EE1TR0lEX0dNX0MyU19DbWQQlE5CAkgDYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.MessageId), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///协议号
  /// </summary>
  public enum MessageId {
    [pbr::OriginalName("MSG_BEGIN")] MsgBegin = 0,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// C2S消息 1000-1999
    ///----------------------------------------------------------------------------------------	
    ///玩家相关协议 1000
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_EnterGame")] MsgidC2SEnterGame = 1000,
    /// <summary>
    ///创建角色
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_CreatePlayer")] MsgidC2SCreatePlayer = 1001,
    /// <summary>
    ///游戏匹配
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_Match")] MsgidC2SMatch = 1002,
    /// <summary>
    ///换装
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ChangeFashion")] MsgidC2SChangeFashion = 1003,
    /// <summary>
    ///取消匹配
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_CancelMatch")] MsgidC2SCancelMatch = 1004,
    /// <summary>
    ///读取邮件
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ReadMail")] MsgidC2SReadMail = 1005,
    /// <summary>
    ///领取邮件
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ReceiveMail")] MsgidC2SReceiveMail = 1006,
    /// <summary>
    ///删除邮件
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_DelMail")] MsgidC2SDelMail = 1007,
    /// <summary>
    ///检查名字合法
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_CheckRoleName")] MsgidC2SCheckRoleName = 1008,
    /// <summary>
    ///继续上局游戏
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ContinueGame")] MsgidC2SContinueGame = 1009,
    /// <summary>
    ///支付
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_Pay")] MsgidC2SPay = 1010,
    /// <summary>
    ///继续游戏
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_Reconnection")] MsgidC2SReconnection = 1011,
    /// <summary>
    ///邀请好友
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_InviteFrient")] MsgidC2SInviteFrient = 1012,
    /// <summary>
    ///请求刷新时间
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ReqShopTime")] MsgidC2SReqShopTime = 1013,
    /// <summary>
    ///请求购买商品
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ReqShopBuy")] MsgidC2SReqShopBuy = 1014,
    /// <summary>
    ///支付订单
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_PayOrder")] MsgidC2SPayOrder = 1015,
    /// <summary>
    ///支付完成
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_PayFinished")] MsgidC2SPayFinished = 1016,
    /// <summary>
    ///改名
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ChangeName")] MsgidC2SChangeName = 1017,
    /// <summary>
    ///改称号
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ChangeTitle")] MsgidC2SChangeTitle = 1018,
    /// <summary>
    ///改签名
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ChangeSignature")] MsgidC2SChangeSignature = 1019,
    /// <summary>
    ///订单查询
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_QueryOrder")] MsgidC2SQueryOrder = 1020,
    /// <summary>
    ///创建队伍
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_CreateTeam")] MsgidC2SCreateTeam = 1030,
    /// <summary>
    ///进入队伍
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_EnterTeam")] MsgidC2SEnterTeam = 1031,
    /// <summary>
    ///退出队伍
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ExitTeam")] MsgidC2SExitTeam = 1032,
    /// <summary>
    ///购买身份卡
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_BuyTagCard")] MsgidC2SBuyTagCard = 1040,
    /// <summary>
    ///设置使用状态
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_SetTagCardState")] MsgidC2SSetTagCardState = 1041,
    /// <summary>
    ///请求抽奖
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_RequestLottery")] MsgidC2SRequestLottery = 1042,
    /// <summary>
    ///购买抽奖币
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_BuyLotteryCoin")] MsgidC2SBuyLotteryCoin = 1043,
    /// <summary>
    ///ngg购买验证
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_NggBuyVerify")] MsgidC2SNggBuyVerify = 1044,
    /// <summary>
    ///断线重连
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_ResetConnect")] MsgidC2SResetConnect = 1998,
    /// <summary>
    ///心跳包
    /// </summary>
    [pbr::OriginalName("MSGID_C2S_HeartBeat")] MsgidC2SHeartBeat = 1999,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// S2C消息 2000-2999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_PlayerInfo")] MsgidS2CPlayerInfo = 2000,
    /// <summary>
    ///创建角色
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_CreatePlayer")] MsgidS2CCreatePlayer = 2001,
    /// <summary>
    ///匹配信息
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_MatchResult")] MsgidS2CMatchResult = 2002,
    /// <summary>
    ///同步其他玩家信息
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_TargetInfo")] MsgidS2CTargetInfo = 2003,
    /// <summary>
    ///换装
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeFashion")] MsgidS2CChangeFashion = 2004,
    /// <summary>
    ///同步部件信息
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_PartsInfo")] MsgidS2CPartsInfo = 2005,
    /// <summary>
    /// 同步邮件列表
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_LoadMailInfo")] MsgidS2CLoadMailInfo = 2006,
    /// <summary>
    /// 读取邮件结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ReadMail")] MsgidS2CReadMail = 2007,
    /// <summary>
    /// 领取邮件道具结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_Receive")] MsgidS2CReceive = 2008,
    /// <summary>
    /// 删除邮件结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_DelMail")] MsgidS2CDelMail = 2009,
    /// <summary>
    /// 开启一个新赛季
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_OpenBattlePass")] MsgidS2COpenBattlePass = 2010,
    /// <summary>
    /// 关闭一个新赛季
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_CloseBattlePass")] MsgidS2CCloseBattlePass = 2011,
    /// <summary>
    /// 等级变动通知
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_BattlePassLv")] MsgidS2CBattlePassLv = 2012,
    /// <summary>
    /// 充值解锁
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_BattlePassPay")] MsgidS2CBattlePassPay = 2013,
    /// <summary>
    /// 检查名字合法
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_CheckRoleName")] MsgidS2CCheckRoleName = 2014,
    /// <summary>
    /// 取消匹配
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_CancelMatch")] MsgidS2CCancelMatch = 2015,
    /// <summary>
    /// 匹配
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_Match")] MsgidS2CMatch = 2016,
    /// <summary>
    /// 支付
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_Pay")] MsgidS2CPay = 2017,
    /// <summary>
    /// 邀请结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_InviteResult")] MsgidS2CInviteResult = 2018,
    /// <summary>
    /// 通知被邀请者
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_InviteNotice")] MsgidS2CInviteNotice = 2019,
    /// <summary>
    /// 获得道具
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_AddItem")] MsgidS2CAddItem = 2020,
    /// <summary>
    /// 货币改变
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeMoney")] MsgidS2CChangeMoney = 2021,
    /// <summary>
    /// 商店刷新信息
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ShopRefNotice")] MsgidS2CShopRefNotice = 2022,
    /// <summary>
    /// 刷新的剩余时间
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ShopRefTime")] MsgidS2CShopRefTime = 2023,
    /// <summary>
    /// 购买结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ShopBuyResult")] MsgidS2CShopBuyResult = 2024,
    /// <summary>
    ///支付完成
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_PayFinished")] MsgidS2CPayFinished = 2025,
    /// <summary>
    ///改名
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeName")] MsgidS2CChangeName = 2026,
    /// <summary>
    ///改称号
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeTitle")] MsgidS2CChangeTitle = 2027,
    /// <summary>
    ///改签名
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeSignature")] MsgidS2CChangeSignature = 2028,
    /// <summary>
    /// 队伍信息
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_TeamInfo")] MsgidS2CTeamInfo = 2030,
    /// <summary>
    /// 进入队伍广播
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_EnterTeam_Broadcast")] MsgidS2CEnterTeamBroadcast = 2031,
    /// <summary>
    /// 退出队伍广播
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ExitTeam_Broadcast")] MsgidS2CExitTeamBroadcast = 2032,
    /// <summary>
    /// 队伍操作结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_Team_Result")] MsgidS2CTeamResult = 2033,
    /// <summary>
    /// 购买身份卡返回结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_BuyTagCard_Ret")] MsgidS2CBuyTagCardRet = 2040,
    /// <summary>
    /// 身份卡数量变动
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeTagCard")] MsgidS2CChangeTagCard = 2041,
    /// <summary>
    /// 身份卡是否在使用中
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_TagCardState")] MsgidS2CTagCardState = 2042,
    /// <summary>
    /// 抽奖结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ResponseLottery")] MsgidS2CResponseLottery = 2043,
    /// <summary>
    /// 抽奖币改变
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ChangeLotteryCoin")] MsgidS2CChangeLotteryCoin = 2044,
    /// <summary>
    /// 购买结果
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_BuyLotteryCoinRet")] MsgidS2CBuyLotteryCoinRet = 2045,
    [pbr::OriginalName("MSGID_S2C_NggBuyVerify")] MsgidS2CNggBuyVerify = 2046,
    [pbr::OriginalName("MSGID_S2C_FirstRecharge")] MsgidS2CFirstRecharge = 2047,
    [pbr::OriginalName("MSGID_S2C_FirstRechargGoods")] MsgidS2CFirstRechargGoods = 2048,
    /// <summary>
    ///断线重连成功
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_ResetConnect")] MsgidS2CResetConnect = 2997,
    /// <summary>
    ///需要重新登录
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_Reload")] MsgidS2CReload = 2998,
    /// <summary>
    ///心跳包返回
    /// </summary>
    [pbr::OriginalName("MSGID_S2C_HeartBeat")] MsgidS2CHeartBeat = 2999,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// C2L消息 3000~3999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_EnterScene")] MsgidC2LEnterScene = 3000,
    /// <summary>
    ///地图信息加载完成
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_LoadMapFinished")] MsgidC2LLoadMapFinished = 3001,
    /// <summary>
    ///移动数据
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_SyncMove")] MsgidC2LSyncMove = 3002,
    /// <summary>
    ///开启讨论
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Meeting")] MsgidC2LMeeting = 3003,
    /// <summary>
    ///死者报告
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_CheckDead")] MsgidC2LCheckDead = 3004,
    /// <summary>
    ///聊天
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Chat")] MsgidC2LChat = 3005,
    /// <summary>
    ///投票
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Vote")] MsgidC2LVote = 3006,
    /// <summary>
    ///开始任务
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_PuzzleStart")] MsgidC2LPuzzleStart = 3007,
    /// <summary>
    ///任务完成
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_PuzzleFinish")] MsgidC2LPuzzleFinish = 3008,
    /// <summary>
    ///任务失败
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_PuzzleFailed")] MsgidC2LPuzzleFailed = 3009,
    /// <summary>
    ///破坏任务
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_DestroyPuzzle")] MsgidC2LDestroyPuzzle = 3010,
    /// <summary>
    ///拾取道具
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_PickupItem")] MsgidC2LPickupItem = 3011,
    /// <summary>
    ///使用道具
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_UseItem")] MsgidC2LUseItem = 3012,
    /// <summary>
    ///跳跃
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Jump")] MsgidC2LJump = 3013,
    /// <summary>
    ///攻击
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Attack")] MsgidC2LAttack = 3014,
    /// <summary>
    ///使用电梯
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_UseLift")] MsgidC2LUseLift = 3015,
    /// <summary>
    ///使用监视器
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_UseMonitor")] MsgidC2LUseMonitor = 3016,
    /// <summary>
    ///取消监视器
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_CancelMonitor")] MsgidC2LCancelMonitor = 3017,
    /// <summary>
    ///语音
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Voice")] MsgidC2LVoice = 3018,
    /// <summary>
    ///钥匙拾取
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_PickUpKey")] MsgidC2LPickUpKey = 3019,
    /// <summary>
    ///会议中移动
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_MeetingMove")] MsgidC2LMeetingMove = 3020,
    /// <summary>
    ///狼人游戏------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_EnterBox")] MsgidC2LEnterBox = 3021,
    /// <summary>
    ///离开箱子
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_LeaveBox")] MsgidC2LLeaveBox = 3022,
    /// <summary>
    ///破坏箱子
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_DestroyBox")] MsgidC2LDestroyBox = 3023,
    /// <summary>
    ///修复箱子
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_RepairBox")] MsgidC2LRepairBox = 3024,
    /// <summary>
    ///修复箱子成功
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_RepairBox_Succeed")] MsgidC2LRepairBoxSucceed = 3025,
    /// <summary>
    ///修复箱子失败
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_RepairBox_Failed")] MsgidC2LRepairBoxFailed = 3026,
    /// <summary>
    ///躲猫猫游戏------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Attack_Stilllife")] MsgidC2LAttackStilllife = 3030,
    /// <summary>
    ///躲猫猫游戏------------------------------------------
    ///格斗吃鸡----------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_UseSkill")] MsgidC2LUseSkill = 3040,
    /// <summary>
    ///传送
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_ToNextRoom")] MsgidC2LToNextRoom = 3041,
    /// <summary>
    ///格斗吃鸡----------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_Reconnection")] MsgidC2LReconnection = 3998,
    /// <summary>
    ///心跳包
    /// </summary>
    [pbr::OriginalName("MSGID_C2L_HeartBeat")] MsgidC2LHeartBeat = 3999,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// L2C消息 4000~4999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_EnterScene")] MsgidL2CEnterScene = 4000,
    /// <summary>
    ///同步玩家信息
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_PlayersInfo_Broadcast")] MsgidL2CPlayersInfoBroadcast = 4001,
    /// <summary>
    ///准备进入讨论
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_WaitMeeting_Broadcast")] MsgidL2CWaitMeetingBroadcast = 4002,
    /// <summary>
    ///移动校验数据
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_SetPos")] MsgidL2CSetPos = 4003,
    /// <summary>
    ///移动数据转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_SyncMove_Broadcast")] MsgidL2CSyncMoveBroadcast = 4004,
    /// <summary>
    ///开启讨论
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Meeting")] MsgidL2CMeeting = 4005,
    /// <summary>
    ///死者报告
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_CheckDead")] MsgidL2CCheckDead = 4006,
    /// <summary>
    ///开启讨论
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Meeting_Broadcast")] MsgidL2CMeetingBroadcast = 4007,
    /// <summary>
    ///聊天转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Chat_Broadcast")] MsgidL2CChatBroadcast = 4009,
    /// <summary>
    ///投票转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Vote_Broadcast")] MsgidL2CVoteBroadcast = 4011,
    /// <summary>
    ///会议结束
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_MeetingOver_Broadcast")] MsgidL2CMeetingOverBroadcast = 4012,
    /// <summary>
    ///语音转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Voice_Broadcast")] MsgidL2CVoiceBroadcast = 4013,
    /// <summary>
    ///任务开始转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_PuzzleStart_Broadcast")] MsgidL2CPuzzleStartBroadcast = 4014,
    /// <summary>
    ///任务完成转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_PuzzleFinish_Broadcast")] MsgidL2CPuzzleFinishBroadcast = 4015,
    /// <summary>
    ///任务失败转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_PuzzleFailed_Broadcast")] MsgidL2CPuzzleFailedBroadcast = 4016,
    /// <summary>
    ///破坏任务转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_DestroyPuzzle_Broadcast")] MsgidL2CDestroyPuzzleBroadcast = 4017,
    /// <summary>
    ///添加buff
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_AddBuff_Broadcast")] MsgidL2CAddBuffBroadcast = 4023,
    /// <summary>
    ///移除buff
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_RemBuff_Broadcast")] MsgidL2CRemBuffBroadcast = 4024,
    /// <summary>
    ///拾取道具结果
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_PickupItem_Broadcast")] MsgidL2CPickupItemBroadcast = 4025,
    /// <summary>
    ///使用道具结果
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_UseItem_Broadcast")] MsgidL2CUseItemBroadcast = 4026,
    /// <summary>
    ///准备开始游戏
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameStartNotices_Broadcast")] MsgidL2CGameStartNoticesBroadcast = 4022,
    /// <summary>
    ///游戏开始
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameStart_Broadcast")] MsgidL2CGameStartBroadcast = 4027,
    /// <summary>
    ///游戏继续
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameContinue_Broadcast")] MsgidL2CGameContinueBroadcast = 4028,
    /// <summary>
    ///游戏结算通知
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameClearingNotices_Broadcast")] MsgidL2CGameClearingNoticesBroadcast = 4029,
    /// <summary>
    ///游戏结算
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameClearing_Broadcast")] MsgidL2CGameClearingBroadcast = 4030,
    /// <summary>
    ///游戏结束
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameOver_Broadcast")] MsgidL2CGameOverBroadcast = 4031,
    /// <summary>
    ///跳跃转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Jump_Broadcast")] MsgidL2CJumpBroadcast = 4032,
    /// <summary>
    ///属性改变转发
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_AttributeChange_Broadcast")] MsgidL2CAttributeChangeBroadcast = 4033,
    /// <summary>
    ///攻击结果
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Attack")] MsgidL2CAttack = 4034,
    /// <summary>
    ///状态同步
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_SyncState_Broadcast")] MsgidL2CSyncStateBroadcast = 4035,
    /// <summary>
    ///使用电梯
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_UseLift_Broadcast")] MsgidL2CUseLiftBroadcast = 4036,
    /// <summary>
    ///使用监视器结果
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_UseMonitor_Broadcast")] MsgidL2CUseMonitorBroadcast = 4037,
    /// <summary>
    ///取消监视器
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_CancelMonitor_Broadcast")] MsgidL2CCancelMonitorBroadcast = 4038,
    /// <summary>
    ///改变游戏时间
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_ChangeGameTime_Broadcast")] MsgidL2CChangeGameTimeBroadcast = 4039,
    /// <summary>
    ///创建一个陷阱
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_CreateTrap_Broadcast")] MsgidL2CCreateTrapBroadcast = 4040,
    /// <summary>
    ///销毁一个陷阱
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_DestroyTrap_Broadcast")] MsgidL2CDestroyTrapBroadcast = 4041,
    /// <summary>
    ///玩家死亡
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Dead_Broadcast")] MsgidL2CDeadBroadcast = 4042,
    /// <summary>
    ///地图信息加载完成
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_LoadMapFinished_Broadcast")] MsgidL2CLoadMapFinishedBroadcast = 4043,
    /// <summary>
    ///核心任务开启
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_CorePuzzle_Open")] MsgidL2CCorePuzzleOpen = 4044,
    /// <summary>
    ///使用道具传送房间
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_TranRoom_Broadcast")] MsgidL2CTranRoomBroadcast = 4045,
    /// <summary>
    ///更新道具状态
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_ItemStateUpdate")] MsgidL2CItemStateUpdate = 4046,
    /// <summary>
    ///钥匙信息
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_KeyData_Broadcast")] MsgidL2CKeyDataBroadcast = 4047,
    /// <summary>
    ///会议中移动
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_MeetingMove_Broadcast")] MsgidL2CMeetingMoveBroadcast = 4048,
    /// <summary>
    ///游戏状态
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameState_Broadcast")] MsgidL2CGameStateBroadcast = 4049,
    /// <summary>
    ///狼人游戏------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_GameStage_Broadcast")] MsgidL2CGameStageBroadcast = 4050,
    /// <summary>
    ///进入箱子
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_EnterBox_Broadcast")] MsgidL2CEnterBoxBroadcast = 4051,
    /// <summary>
    ///离开箱子
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_LeaveBox_Broadcast")] MsgidL2CLeaveBoxBroadcast = 4052,
    /// <summary>
    ///破坏箱子
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_DestroyBox_Broadcast")] MsgidL2CDestroyBoxBroadcast = 4053,
    /// <summary>
    ///修复箱子
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_RepairBox_Broadcast")] MsgidL2CRepairBoxBroadcast = 4054,
    /// <summary>
    ///修复箱子成功
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_RepairBox_Succeed_Broadcast")] MsgidL2CRepairBoxSucceedBroadcast = 4055,
    /// <summary>
    ///修复箱子失败
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_RepairBox_Failed_Broadcast")] MsgidL2CRepairBoxFailedBroadcast = 4056,
    /// <summary>
    ///身份改变
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_JobChange_Broadcast")] MsgidL2CJobChangeBroadcast = 4057,
    /// <summary>
    ///躲猫猫游戏------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Attack_Stilllife_Broadcast")] MsgidL2CAttackStilllifeBroadcast = 4060,
    /// <summary>
    ///躲猫猫游戏------------------------------------------
    ///格斗吃鸡----------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_UseSkill_Broadcast")] MsgidL2CUseSkillBroadcast = 4070,
    /// <summary>
    ///传送
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_ToNextRoom_Broadcast")] MsgidL2CToNextRoomBroadcast = 4071,
    /// <summary>
    ///连接无效（游戏结束）
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_ConnectionInvalid")] MsgidL2CConnectionInvalid = 4997,
    /// <summary>
    ///断线重连
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_Reconnection")] MsgidL2CReconnection = 4998,
    /// <summary>
    ///心跳包
    /// </summary>
    [pbr::OriginalName("MSGID_L2C_HeartBeat")] MsgidL2CHeartBeat = 4999,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// C2A消息 5000~5999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_C2A_Auth")] MsgidC2AAuth = 5000,
    /// <summary>
    ///账号登录
    /// </summary>
    [pbr::OriginalName("MSGID_C2A_SteamAuth")] MsgidC2ASteamAuth = 5001,
    [pbr::OriginalName("MSGID_C2A_WeGameAuth")] MsgidC2AWeGameAuth = 5002,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// A2C消息 6000~6999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_A2C_Auth")] MsgidA2CAuth = 6000,
    /// <summary>
    ///---------服务器间消息--------------------------------------------------------------------
    ///----------------------------------------------------------------------------------------
    /// W2S消息 7000~7499
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_W2S_RequestEnter")] MsgidW2SRequestEnter = 7000,
    /// <summary>
    ///支付完成回复
    /// </summary>
    [pbr::OriginalName("MSGID_W2S_PayFinished")] MsgidW2SPayFinished = 7001,
    /// <summary>
    ///支付完成添加道具
    /// </summary>
    [pbr::OriginalName("MSGID_W2S_AddItem")] MsgidW2SAddItem = 7002,
    /// <summary>
    ///购买验证结果
    /// </summary>
    [pbr::OriginalName("MSGID_W2S_NggBuyVerify")] MsgidW2SNggBuyVerify = 7003,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// S2W消息 7500~7999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_S2W_RequestEnter")] MsgidS2WRequestEnter = 7500,
    /// <summary>
    ///支付订单
    /// </summary>
    [pbr::OriginalName("MSGID_S2W_PayOrder")] MsgidS2WPayOrder = 7501,
    /// <summary>
    ///支付完成
    /// </summary>
    [pbr::OriginalName("MSGID_S2W_PayFinished")] MsgidS2WPayFinished = 7502,
    /// <summary>
    ///支付完成添加道具返回
    /// </summary>
    [pbr::OriginalName("MSGID_S2W_AddItem")] MsgidS2WAddItem = 7503,
    /// <summary>
    ///订单查询
    /// </summary>
    [pbr::OriginalName("MSGID_S2W_QueryOrder")] MsgidS2WQueryOrder = 7504,
    [pbr::OriginalName("MSGID_S2W_NggBuyVerify")] MsgidS2WNggBuyVerify = 7505,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// S2G消息 8000~8499
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_S2G_AddPlayerInfo")] MsgidS2GAddPlayerInfo = 8000,
    /// <summary>
    ///删除用户
    /// </summary>
    [pbr::OriginalName("MSGID_S2G_DelPlayerInfo")] MsgidS2GDelPlayerInfo = 8001,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// G2S消息 8500~8999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_G2S_PlayerOffline")] MsgidG2SPlayerOffline = 8500,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// L2S消息 9000~9499
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_L2S_CreateScene")] MsgidL2SCreateScene = 9000,
    /// <summary>
    ///游戏结果
    /// </summary>
    [pbr::OriginalName("MSGID_L2S_GameResult")] MsgidL2SGameResult = 9001,
    /// <summary>
    ///玩家死亡
    /// </summary>
    [pbr::OriginalName("MSGID_L2S_PlayerDead")] MsgidL2SPlayerDead = 9002,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// S2L消息 9500~9999
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_S2L_CreateScene")] MsgidS2LCreateScene = 9500,
    /// <summary>
    ///进入场景
    /// </summary>
    [pbr::OriginalName("MSGID_S2L_EnterScene")] MsgidS2LEnterScene = 9501,
    /// <summary>
    ///----------------------------------------------------------------------------------------
    /// gm消息 10000~11000
    ///----------------------------------------------------------------------------------------
    /// </summary>
    [pbr::OriginalName("MSGID_GM_C2S_Login")] MsgidGmC2SLogin = 10000,
    /// <summary>
    ///登录 ret
    /// </summary>
    [pbr::OriginalName("MSGID_GM_S2C_Login")] MsgidGmS2CLogin = 10001,
    /// <summary>
    ///发送邮件
    /// </summary>
    [pbr::OriginalName("MSGID_GM_C2S_Mail")] MsgidGmC2SMail = 10002,
    /// <summary>
    ///gm执行结果
    /// </summary>
    [pbr::OriginalName("MSGID_GM_S2C_Result")] MsgidGmS2CResult = 10003,
    /// <summary>
    ///gm通用命令
    /// </summary>
    [pbr::OriginalName("MSGID_GM_C2S_Cmd")] MsgidGmC2SCmd = 10004,
  }

  #endregion

}

#endregion Designer generated code
