
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public item.TbItem TbItem {get; }
    public TbGameConst TbGameConst {get; }
    public ui.TbUILayer TbUILayer {get; }
    public ui.TbUIPanel TbUIPanel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbGameConst = new TbGameConst(loader("tbgameconst"));
        TbUILayer = new ui.TbUILayer(loader("ui_tbuilayer"));
        TbUIPanel = new ui.TbUIPanel(loader("ui_tbuipanel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbGameConst.ResolveRef(this);
        TbUILayer.ResolveRef(this);
        TbUIPanel.ResolveRef(this);
    }
}

}
